checkpoint_path: ./outputs/train/debug
dataset_root: ./outputs/cache/debug
output_root: ./outputs/eval/debug
run_offline: true
run_rollout: false
split: val
batch_size: 8
max_steps: 128
limit_episodes: 1
control_timestep: 0.05
n_steps_lookahead: 1
environment_name: RoboPianist-debug-TwinkleTwinkleLittleStar-v0
wandb:
  enabled: true
  entity: tnguyen31-santa-clara-university
  project: robopianist
  mode: online
  group: robodiffusion-evaluation
  tags:
    - robodiffusion
    - eval
    - debug
